groups:
  dbci:
    # BGSObs:
    #   subjects: [1, 2, 3]
    #   trials: eval(np.arange(1, 11))
    #   data_file: eeg-order2-low0.1.csv
    #   true_fs: False
    #   # preload_epoch_indexes: 
    #   #   generate_sync_epochs: null
    #   # preload_epoch_indexes:
    #   #   generate_async_epochs:
    #   #     step_size: 100
    #   #     map_type: down
    BGSInt:
      subjects: [5]
      trials: eval(np.arange(5, 5+1))
      data_file: eeg-order2-low0.1.csv
      true_fs: False

    # OAObs:
    #   subjects: [1, 2, 3]
    #   trials: eval(np.arange(1, 11))
    #   data_file: eeg-order2-low0.1.csv
    #   true_fs: False

    # OAOut:
    #   subjects: [1, 2, 3]
    #   trials: eval(np.arange(1, 11))
    #   data_file: eeg-order2-low0.1.csv
      
mutate:
# - apply_func:
#     select: 
#     - [dbci]
#     func:
#     - epochs:
#         tmin: -0.2
#         tmax: .995
#         preload: True
#         picks: [eeg]
#         verbose: True
#         baseline: Null
# - apply_func:
#     select:
#     - [dbci]
#     - [BGSObs, BGSInt, OAObs, OAOut]
#     - [1]
#     func:
#     - reject_epochs:
#         reject: {eeg: 100}
# - apply_func:
#     select:
#     - [dbci]
#     - [BGSObs, BGSInt, OAObs, OAOut]
#     - [2]
#     func:
#     - reject_epochs:
#         reject: {eeg: 100}
# - apply_func:
#     select:
#     - [dbci]
#     - [BGSObs, BGSInt, OAObs, OAOut]
#     - [3]
#     func:
#     - reject_epochs:
#         reject:  {eeg: 100}
# - compress:
#     compress_level: subject

