logo_level: ['dataset', 'subject', 'trial']

seed: 0

model_wrapper:
  _target_: deepbci.models.wrappers.Keras
  model: 
    _target_: deepbci.models.networks.EEGNet
    fs: 128
    chs: 4
    windows: 1
    n_classes: 2
    drop_rate: .5
    conv_kern_len: 64
    conv_filters: 8
    depthwise_filters: 2
    separable_filters: 16
    norm_rate: .25
    drop_type: dropout
    avg_kern_b1: 4
    avg_kern_b2: 8
  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: .01
    # learning_rate: !Tunable 
    #   values: [.01, .001] 
    #   name: learning rate
  loss: 
    _target_: tensorflow.keras.losses.CategoricalCrossentropy
    name: cross_entropy
  metrics:
  - _target_: deepbci.models.metrics.keras.BalancedAccuracy
    name: bACC
  - _target_: tensorflow.keras.metrics.CategoricalAccuracy
    name: ACC
  callbacks:
  - _target_: tensorflow.keras.callbacks.TensorBoard
    log_dir: tensorboard
  - _target_: deepbci.models.callbacks.keras.LogToFile

preinstantiate:
  allow_growth: True

dataset:
  batch_size: 512
  shuffle: True

fit:
  epochs: 1
  # epochs: !Tunable 
  #   values: [25, 50] 
  #   name: epochs
  verbose: 1
  class_weight: 
    _target_: deepbci.utils.class_weight.compute_class_weight
    y: ${get_labels:train}

save:
  filepath: ${join:models,model}
  weights_only: False

evaluate_metrics:
  csv:
    bACC:
      _partial_: True
      _target_: sklearn.metrics.balanced_accuracy_score
    ACC:
      _partial_: True
      _target_: sklearn.metrics.accuracy_score
    tpr:
      _partial_: True
      _target_: sklearn.metrics.recall_score
    ppv:
      _partial_: True
      _target_: sklearn.metrics.precision_score
    tnr:
      _partial_: True
      _target_: sklearn.metrics.recall_score
      pos_label: 0
    F1: 
      _partial_: True
      _target_: sklearn.metrics.f1_score
    nll:
      _partial_: True
      _target_: sklearn.metrics.log_loss
    PR:
      _partial_: True
      _target_: deepbci.models.metrics.prc_auc_score
      column: 1
      pos_label: 1
    ROC:
      _partial_: True
      _target_: deepbci.models.metrics.roc_auc_score
      column: 1
      pos_label: 1
    confusion_matrix:
      _partial_: True
      _target_: sklearn.metrics.confusion_matrix
  log:
    - confusion_matrix
  argmax_axis: 1
  exclude_argmax:
    - nll
    - PR
    - ROC
