duration: 1800 # Number states needed to be captured before ending
before_start: 30 # time before game starts
logging: True

# Game mechanics
scale: 2
fps: 60 # Target FPS 
recording_interval: 100 # rate to record state information in milliseconds
screen_width: 420 # width of the game screen
screen_height: 420 # height of the game screen
state_width: 420
state_height: 420
freeze_duration: 1 # time in seconds player freezes for after collision
ball_limit: 40 # potential number of balls on screen at once
spawn_rate: 70 # rate at which balls spawn (scales with FPS)
player_size: 7 # player radius
player_up: 19 # distance player travels when moving up
player_down: 65 # gravity effect on player
ball_size: 11 # ball radius
ball_speed: 150 # speed balls move
collide_top: 9 # pixel boundary for colliding with the top of the screen 
collide_bottom: 5 # pixel boundary for colliding with the bottom of the screen
collide_ball: 15 # pixel boundary for colliding with a ball
base_reward: 0 # DO NOT CHANGE!
collision_reward: 1 # DO NOT CHANGE! (This is the ground truth target!)
