# @package _global_

defaults:
  - model_wrapper: ???
  - data_loading: ???
  - directory_structure: default
  - _self_


# Stage you are currently in. Can be either train or test.
stage: ???
# Name of the job you are about to run. Can be any name you want.
job_name: ???
# # Description of job when using multi-run
# job_description: ${hydra:job.num}

# Print a rich (i.e., pretty) version of the config to the Python logger.
# Set print_config to null to disable or remove file path to log to console.
print_config:
  file: ${hydra:job_logging.handlers.file.filename}

hydra:
  job:
    name: ${job_name}
  job_logging:
    version: 1
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        level: DEBUG
      file:
        class: logging.FileHandler
        filename: exp_log.log
        level: DEBUG
        mode: 'w'
    root:
      handlers: [console, file]
      level: INFO
    disable_existing_loggers: False
  # Outputs all logs and metrics from training and testing to the below path. Recall,
  # Hydra will overwrite the default directory to the below.
  run:
    dir: ${stage_path}
  sweep:
    dir: ${working_exp_path}
    subdir: ${stage}